// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260429044953_AddNotifications")]
    partial class AddNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Bio")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("AuthorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Name" }, "idx_Name");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Backend.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Advisor")
                        .HasColumnType("longtext");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DDCCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DefenseYear")
                        .HasColumnType("int");

                    b.Property<string>("Degree")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("DownloadCount")
                        .HasColumnType("int");

                    b.Property<int?>("EndPage")
                        .HasColumnType("int");

                    b.Property<string>("Faculty")
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<decimal?>("FileSize")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("IsBorrowable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsPublic")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<short?>("PublishedYear")
                        .HasColumnType("year(4)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Source")
                        .HasColumnType("longtext");

                    b.Property<int?>("StartPage")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("TotalPages")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("University")
                        .HasColumnType("longtext");

                    b.HasKey("BookId")
                        .HasName("PRIMARY");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DDCCode");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("LanguageId");

                    b.HasIndex(new[] { "ISBN" }, "idx_ISBN")
                        .IsUnique();

                    b.HasIndex(new[] { "Title" }, "idx_Title");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Backend.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int(11)");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");
                });

            modelBuilder.Entity("Backend.Models.BookCategory", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int(11)");

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BookCategories");
                });

            modelBuilder.Entity("Backend.Models.BookCopy", b =>
                {
                    b.Property<int>("CopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CopyId"));

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("BookCondition")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("'Good'");

                    b.Property<int?>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<bool>("IsReferenceOnly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShelfLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("CopyId")
                        .HasName("PRIMARY");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "Barcode" }, "Barcode")
                        .IsUnique();

                    b.HasIndex(new[] { "BookId" }, "idx_BookId");

                    b.HasIndex(new[] { "Status" }, "idx_Status");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("Backend.Models.BookCopyStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ChangedById")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CopyId")
                        .HasColumnType("int(11)");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OldStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("CopyId");

                    b.ToTable("BookCopyStatusHistories");
                });

            modelBuilder.Entity("Backend.Models.BookLanguage", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("BookLanguageId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("BookLanguages");
                });

            modelBuilder.Entity("Backend.Models.BorrowPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AspNetRoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("FinePerDay")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaxBooks")
                        .HasColumnType("int");

                    b.Property<int>("MaxBorrowDays")
                        .HasColumnType("int");

                    b.Property<int>("MaxExtention")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("AspNetRoleId", "DocumentTypeId")
                        .IsUnique();

                    b.ToTable("BorrowPolicies");
                });

            modelBuilder.Entity("Backend.Models.BorrowRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("ExpectedBorrowDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("RequestId");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("BookId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowRequests");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PRIMARY");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Backend.Models.DDC", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentCode")
                        .HasColumnType("varchar(20)");

                    b.HasKey("Code")
                        .HasName("PRIMARY");

                    b.HasIndex("ParentCode");

                    b.ToTable("DDC", (string)null);
                });

            modelBuilder.Entity("Backend.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Backend.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FineId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PaidByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TransactionId")
                        .HasColumnType("int(11)");

                    b.HasKey("FineId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "PaidByUserId" }, "PaidByUserId");

                    b.HasIndex(new[] { "Status" }, "idx_Status")
                        .HasDatabaseName("idx_Status1");

                    b.HasIndex(new[] { "TransactionId" }, "idx_TransactionId");

                    b.ToTable("Fines");
                });

            modelBuilder.Entity("Backend.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Backend.Models.ReadingProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<int?>("CurrentPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("HighLights")
                        .HasColumnType("json")
                        .HasComment("[{\"page\":45, \"text\": \"highlight\"}]");

                    b.Property<DateTime?>("LastReadDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PercentRead")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("ProgressId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "BookId");

                    b.HasIndex(new[] { "LastReadDate" }, "idx_LastReadDate");

                    b.HasIndex(new[] { "UserId" }, "idx_UserId");

                    b.HasIndex(new[] { "UserId", "BookId" }, "unique_user_book")
                        .IsUnique();

                    b.ToTable("ReadingProgress", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Recomendation", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecId"));

                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("GeneratedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsViewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasComment("AI explanation");

                    b.Property<decimal>("Score")
                        .HasPrecision(4, 3)
                        .HasColumnType("decimal(4,3)")
                        .HasComment("0.000-1.000 similarity");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("RecId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "BookId")
                        .HasDatabaseName("BookId1");

                    b.HasIndex(new[] { "UserId" }, "idx_UserId")
                        .HasDatabaseName("idx_UserId1");

                    b.HasIndex(new[] { "GeneratedDate" }, "inx_GeneratedDate");

                    b.ToTable("Recomendations");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Backend.Models.StaffProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Position")
                        .HasColumnType("longtext");

                    b.Property<string>("StaffCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("Backend.Models.StudentProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("AdmissionYear")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<string>("Faculty")
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Term")
                        .HasColumnType("longtext");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("Backend.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("CopyId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("int");

                    b.Property<string>("LibrarianId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("ReturnCondition")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ReturnLibrarianId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("TransactionId")
                        .HasName("PRIMARY");

                    b.HasIndex("RequestId");

                    b.HasIndex("ReturnLibrarianId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "LibrarianId" }, "LibrarianId");

                    b.HasIndex(new[] { "BorrowDate" }, "idx_BorrowDate");

                    b.HasIndex(new[] { "CopyId" }, "idx_CopyId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Backend.Models.UserFavoriteBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "BookId")
                        .HasDatabaseName("BookId2");

                    b.HasIndex(new[] { "UserId" }, "idx_UserId")
                        .HasDatabaseName("idx_UserId2");

                    b.HasIndex(new[] { "UserId", "BookId" }, "unique_user_book")
                        .IsUnique()
                        .HasDatabaseName("unique_user_book1");

                    b.ToTable("UserFavoriteBooks");
                });

            modelBuilder.Entity("Backend.Models.UserReadingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasComment("Read/Borrowed/Liked/Rated");

                    b.Property<int?>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.HasKey("HistoryId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "BookId")
                        .HasDatabaseName("BookId3");

                    b.HasIndex(new[] { "CreatedAt" }, "idx_CreatedAt");

                    b.HasIndex(new[] { "UserId" }, "idx_UserId")
                        .HasDatabaseName("idx_UserId3");

                    b.ToTable("UserReadingHistory", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WarehouseId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("Backend.Models.vw_BookAvailability", b =>
                {
                    b.Property<long>("AvailableCopies")
                        .HasColumnType("bigint(21)");

                    b.Property<string>("AvailableLocations")
                        .HasColumnType("text");

                    b.Property<int>("BookId")
                        .HasColumnType("int(11)");

                    b.Property<string>("BookLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<int?>("TotalCopies")
                        .HasColumnType("int(11)")
                        .HasDefaultValueSql("'1'");

                    b.ToTable((string)null);

                    b.ToView("vw_BookAvailability", (string)null);
                });

            modelBuilder.Entity("Backend.Models.vw_StudentStat", b =>
                {
                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("varchar(450)");

                    b.Property<string>("LibraryStatus")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValueSql("'Active'")
                        .HasComment("LIBRARY: Active/Suspended/Expired/Blacklisted");

                    b.Property<string>("StudentClass")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<long>("TotalBorrows")
                        .HasColumnType("bigint(21)");

                    b.Property<decimal?>("TotalFines")
                        .HasPrecision(32, 2)
                        .HasColumnType("decimal(32,2)");

                    b.ToTable((string)null);

                    b.ToView("vw_StudentStats", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Backend.Models.Book", b =>
                {
                    b.HasOne("Backend.Models.Category", null)
                        .WithMany("Books")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Backend.Models.DDC", "DDC")
                        .WithMany("Books")
                        .HasForeignKey("DDCCode");

                    b.HasOne("Backend.Models.DocumentType", "DocumentType")
                        .WithMany("Books")
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Language", null)
                        .WithMany("Books")
                        .HasForeignKey("LanguageId");

                    b.Navigation("DDC");

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("Backend.Models.BookAuthor", b =>
                {
                    b.HasOne("Backend.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Backend.Models.BookCategory", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("BookCategories")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("BookCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.BookCopy", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("BookCopies_ibfk_1");

                    b.HasOne("Backend.Models.Warehouse", "Warehouse")
                        .WithMany("BookCopies")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Backend.Models.BookCopyStatusHistory", b =>
                {
                    b.HasOne("ApplicationUser", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById");

                    b.HasOne("Backend.Models.BookCopy", "Copy")
                        .WithMany("StatusHistories")
                        .HasForeignKey("CopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Copy");
                });

            modelBuilder.Entity("Backend.Models.BookLanguage", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("BookLanguages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Language", "Language")
                        .WithMany("BookLanguages")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Backend.Models.BorrowPolicy", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("AspNetRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Backend.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Backend.Models.BorrowRequest", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("BorrowRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.DDC", b =>
                {
                    b.HasOne("Backend.Models.DDC", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentCode");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Backend.Models.Fine", b =>
                {
                    b.HasOne("ApplicationUser", "PaidByUser")
                        .WithMany("Fines")
                        .HasForeignKey("PaidByUserId")
                        .HasConstraintName("Fines_ibfk_2");

                    b.HasOne("Backend.Models.Transaction", "Transaction")
                        .WithMany("Fines")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Fines_ibfk_1");

                    b.Navigation("PaidByUser");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Backend.Models.Notification", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.ReadingProgress", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("ReadingProgress_ibfk_1");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("ReadingProgresses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("ReadingProgress_ibfk_2");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Recomendation", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("Recomendations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("Recomendations_ibfk_2");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("Recomendations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("Recomendations_ibfk_1");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.RefreshToken", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.StaffProfile", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithOne("StaffProfile")
                        .HasForeignKey("Backend.Models.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.StudentProfile", b =>
                {
                    b.HasOne("ApplicationUser", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("Backend.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.Transaction", b =>
                {
                    b.HasOne("Backend.Models.BookCopy", "Copy")
                        .WithMany("Transactions")
                        .HasForeignKey("CopyId")
                        .HasConstraintName("Transactions_ibfk_2");

                    b.HasOne("ApplicationUser", "Librarian")
                        .WithMany("ManagedTransactions")
                        .HasForeignKey("LibrarianId")
                        .HasConstraintName("Transactions_ibfk_3");

                    b.HasOne("Backend.Models.BorrowRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.HasOne("ApplicationUser", "ReturnLibrarian")
                        .WithMany()
                        .HasForeignKey("ReturnLibrarianId");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("BorrowTransactions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Transactions_ibfk_1");

                    b.Navigation("Copy");

                    b.Navigation("Librarian");

                    b.Navigation("Request");

                    b.Navigation("ReturnLibrarian");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserFavoriteBook", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("UserFavoriteBooks")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("UserFavoriteBooks_ibfk_2");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("UserFavoriteBooks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("UserFavoriteBooks_ibfk_1");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Backend.Models.UserReadingHistory", b =>
                {
                    b.HasOne("Backend.Models.Book", "Book")
                        .WithMany("UserReadingHistories")
                        .HasForeignKey("BookId")
                        .HasConstraintName("UserReadingHistory_ibfk_2");

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("UserReadingHistories")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("UserReadingHistory_ibfk_1");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("BorrowRequests");

                    b.Navigation("BorrowTransactions");

                    b.Navigation("Fines");

                    b.Navigation("ManagedTransactions");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("Recomendations");

                    b.Navigation("StaffProfile")
                        .IsRequired();

                    b.Navigation("StudentProfile")
                        .IsRequired();

                    b.Navigation("UserFavoriteBooks");

                    b.Navigation("UserReadingHistories");
                });

            modelBuilder.Entity("Backend.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("Backend.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BookCategories");

                    b.Navigation("BookCopies");

                    b.Navigation("BookLanguages");

                    b.Navigation("BorrowRequests");

                    b.Navigation("ReadingProgresses");

                    b.Navigation("Recomendations");

                    b.Navigation("UserFavoriteBooks");

                    b.Navigation("UserReadingHistories");
                });

            modelBuilder.Entity("Backend.Models.BookCopy", b =>
                {
                    b.Navigation("StatusHistories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("BookCategories");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("Backend.Models.DDC", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("Backend.Models.DocumentType", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Backend.Models.Language", b =>
                {
                    b.Navigation("BookLanguages");

                    b.Navigation("Books");
                });

            modelBuilder.Entity("Backend.Models.Transaction", b =>
                {
                    b.Navigation("Fines");
                });

            modelBuilder.Entity("Backend.Models.Warehouse", b =>
                {
                    b.Navigation("BookCopies");
                });
#pragma warning restore 612, 618
        }
    }
}
